project:
  type: website
  output-dir: docs

website:
  title: "How to Solve It"
  site-url: https://canonakym.github.io/how-to-solve-it/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Data Analysis
        menu:
          - href: how_to_solve_it_data_analysis/qmd_script/how_to_solve_it_data_analysis_index.qmd
            text: Overview
          - href: how_to_solve_it_data_analysis/qmd_script/how_to_solve_it_data_analysis_session0.qmd
            text: Session 0
          - href: how_to_solve_it_data_analysis/qmd_script/how_to_solve_it_data_analysis_session1.qmd
            text: Session 1

format:
  html:
    toc: true
    css: styles.css
    
crossref:
  lst-title: "コード"
  lst-prefix: "コード"
  