project:
  type: website
  output-dir: docs
  resources: 
    - data_analysis/demo_dataset/*.csv

website:
  title: "How to Solve It"
  site-url: https://canonakym.github.io/how-to-solve-it/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Data Analysis
        menu:
          - href: data_analysis/index.qmd
            text: Overview
          - href: data_analysis/session0.qmd
            text: Session 0
          - href: data_analysis/session1.qmd
            text: Session 1

format:
  html:
    toc: true
    css: styles.css

crossref:
  lst-title: "コード"
  lst-prefix: "コード"
  